/**
 * \file main.c
 * \brief main file for the CanNode project for Cedarville Supermileage.
 * Automatically generated by STCubeMX then hacked beyond recognition by 
 * Samuel Ellicott
 *
 * \author Samuel Ellicott
 * \date 6-8-16
 */

#include <stdint.h>
#include <stm32f0xx_hal.h>
#include <stdlib.h>
#include <string.h>
#include <can.h>
#include <CanNode.h>

#include "usb_device.h"
#include "usbd_cdc_if.h"

#define IO1_ADC ADC_CHSELR_CHSEL6
#define IO2_ADC ADC_CHSELR_CHSEL7
#define IO3_ADC ADC_CHSELR_CHSEL9

//transmit code or recieve code
#define RECIEVE

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
void MX_GPIO_Init(void);
void MX_NVIC_Init(void);
void MX_ADC_Init(void);

/* Private function prototypes -----------------------------------------------*/
void countRTR(CanMessage* data);
void timeRTR(CanMessage* data);

ADC_HandleTypeDef hadc;

CanNode* wheelCountNode;
CanNode* wheelTimeNode;
volatile uint8_t  wheelCount;
volatile uint32_t wheelTime;

int main(void) {
	wheelCount=0;
	wheelTime=0;
	uint16_t switchState=0;
	uint16_t buff_len = 50;
	uint8_t buff[50];
	uint16_t data;
	int16_t adcVal;

	// Reset of all peripherals, Initializes the Flash interface and the Systick.
	HAL_Init();

	// Configure the system clock
	SystemClock_Config();

	// Initialize all configured peripherals
	MX_GPIO_Init();
	MX_NVIC_Init();
    	MX_USB_DEVICE_Init();
	MX_ADC_Init();

    
	wheelCountNode = CanNode_init(WHEEL_TACH, countRTR, true);
	wheelTimeNode = CanNode_init(WHEEL_TIME, timeRTR, true);

	//setup name/info strings
	const char* wheelCountName = "Wheel revolution count";
	const char* wheelCountInfo = "Gives the number of wheel revolutions in the "
		                         "last second.";
	CanNode_setName(wheelCountNode, wheelCountName, sizeof(wheelCountName));
	CanNode_setInfo(wheelCountNode, wheelCountInfo, sizeof(wheelCountInfo));

	const char* wheelTimeName = "Wheel rotation time";
	const char* wheelTimeInfo = "Gives the ammount of time that the previous "
		                        "Wheel revolution took.";
	CanNode_setName(wheelTimeNode, wheelTimeName, sizeof(wheelTimeName));
	CanNode_setInfo(wheelTimeNode, wheelTimeInfo, sizeof(wheelTimeInfo));
	

	while (1) {
		//get the current time
		HAL_Delay(1);
		uint32_t time = HAL_GetTick();
		//check if there is a message necessary for CanNode functionality
		CanNode_checkForMessages();

		HAL_ADC_Start(&hadc);
        	HAL_ADC_PollForConversion(&hadc, 5);
		adcVal = HAL_ADC_GetValue(&hadc);
		switchState = IO1_GPIO_Port->IDR & IO1_Pin;



		if(switchState){
			LED2_GPIO_Port->ODR |= LED2_Pin;
			switchState = 1;
		}
		else{
			LED2_GPIO_Port->ODR &= ~LED2_Pin;
			switchState = 0;
		}


		//send time data once every 0.5s
		if(time % 500 == 0){
			CanNode_sendData_uint32(wheelTimeNode, wheelTime);
			itoa(adcVal, buff, 10);
			strcat(buff, "\n\r");
			if(switchState){
				strcat(buff, "on\n\r");
			}
			else {
				strcat(buff, "off\n\r");
			}
			CDC_Transmit_FS(buff, strlen(buff));
		}
		//send and reset count varible every second
		if(time % 1000 == 0){
			CanNode_sendData_uint8(wheelCountNode, wheelCount);
			wheelCount=0;
			HAL_GPIO_TogglePin(GPIOB, LED1_Pin);
		}
	}
}

void countRTR(CanMessage* data){
	CanNode_sendData_uint8(wheelCountNode, wheelCount);
}

void timeRTR(CanMessage* data){
	CanNode_sendData_uint32(wheelTimeNode, wheelTime);
}

//callback for pin6 (IO1) interrupt

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin) {
	static uint32_t startTime=0;
	uint32_t newTime = HAL_GetTick();
	uint32_t tempTime = newTime - startTime;
	
	//if the supposed time it takes for the wheel to go around is less than
	//31/32 of the last time then it is just contact bounce and should be 
	//ignored
	if(tempTime < wheelTime-(wheelTime>>5) ) {
	    return;
	}
	//get the elapsed time
	wheelTime = tempTime;
	//set the new start time
	startTime = newTime;
	//increment the wheel count
	++wheelCount;
	//toggle led
	LED2_GPIO_Port->ODR ^= LED2_Pin;
}

/** System Clock Configuration
*/

/** System Clock Configuration
*/
void SystemClock_Config(void)
{

	RCC_OscInitTypeDef RCC_OscInitStruct;
	RCC_ClkInitTypeDef RCC_ClkInitStruct;
	RCC_PeriphCLKInitTypeDef PeriphClkInit;

	RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI14|RCC_OSCILLATORTYPE_HSI48;
	RCC_OscInitStruct.HSI48State = RCC_HSI48_ON;
	RCC_OscInitStruct.HSI14State = RCC_HSI14_ON;
	RCC_OscInitStruct.HSI14CalibrationValue = 16;
	RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;
	HAL_RCC_OscConfig(&RCC_OscInitStruct);

	RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
		              |RCC_CLOCKTYPE_PCLK1;
	RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI48;
	RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
	RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
	HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1);

	PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_USB;
	PeriphClkInit.UsbClockSelection = RCC_USBCLKSOURCE_HSI48;
	HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit);

	HAL_SYSTICK_Config(HAL_RCC_GetHCLKFreq()/1000);

	HAL_SYSTICK_CLKSourceConfig(SYSTICK_CLKSOURCE_HCLK);

	/* SysTick_IRQn interrupt configuration */
	HAL_NVIC_SetPriority(SysTick_IRQn, 0, 0);
}

/* ADC init function */
void MX_ADC_Init(void) {
  ADC_ChannelConfTypeDef sConfig;

    /**Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
    */
  hadc.Instance = ADC1;
  hadc.Init.ClockPrescaler = ADC_CLOCK_ASYNC_DIV1;
  hadc.Init.Resolution = ADC_RESOLUTION_12B;
  hadc.Init.DataAlign = ADC_DATAALIGN_RIGHT;
  hadc.Init.ScanConvMode = ADC_SCAN_DIRECTION_FORWARD;
  hadc.Init.EOCSelection = ADC_EOC_SINGLE_CONV;
  hadc.Init.LowPowerAutoWait = DISABLE;
  hadc.Init.LowPowerAutoPowerOff = DISABLE;
  hadc.Init.ContinuousConvMode = DISABLE;
  hadc.Init.DiscontinuousConvMode = ENABLE;
  hadc.Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_NONE;
  hadc.Init.DMAContinuousRequests = DISABLE;
  hadc.Init.Overrun = ADC_OVR_DATA_PRESERVED;
  HAL_ADC_Init(&hadc);

    /**Configure for the selected ADC regular channel to be converted.
    */
  sConfig.Channel = ADC_CHANNEL_7;
  sConfig.Rank = ADC_RANK_CHANNEL_NUMBER;
  sConfig.SamplingTime = ADC_SAMPLETIME_1CYCLE_5;
  HAL_ADC_ConfigChannel(&hadc, &sConfig);

}


/** Configure pins as
        * Analog
        * Input
        * Output
        * EVENT_OUT
        * EXTI
        * Free pins are configured automatically as Analog (this feature is enabled through 
        * the Code Generation settings)
*/
void MX_GPIO_Init(void)
{

    GPIO_InitTypeDef GPIO_InitStruct;

    /* GPIO Ports Clock Enable */
    __HAL_RCC_GPIOC_CLK_ENABLE();
    __HAL_RCC_GPIOF_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    /*Configure GPIO pins : PC13 PC14 PC15 */
    GPIO_InitStruct.Pin = GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15;
    GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);

    /*Configure GPIO pins : PF0 PF1 PF11 */
    GPIO_InitStruct.Pin = GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_11;
    GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOF, &GPIO_InitStruct);

    /*Configure GPIO pins : PA0 PA1 PA2 PA3
                           PA4 PA5 PA6 PA8
                           PA9 PA10 PA15 */
    GPIO_InitStruct.Pin = GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3
                          |GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6|GPIO_PIN_8
                          |GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_15;
    GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    /*Configure GPIO pins : PB1 PB2 PB10 PB11
                           PB12 PB13 PB14 PB15
                           PB5 PB6 PB7 */
    GPIO_InitStruct.Pin = GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_10|GPIO_PIN_11
                          |GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15
                          |GPIO_PIN_5|GPIO_PIN_6|GPIO_PIN_7;
    GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    /*Configure GPIO pins : LED2_Pin LED1_Pin */
    GPIO_InitStruct.Pin = LED2_Pin|LED1_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    /*Configure GPIO pin Output Level */
    HAL_GPIO_WritePin(GPIOB, LED2_Pin|LED1_Pin, GPIO_PIN_SET);


    //configure IO1 as a rising edge interrupt pin
	GPIO_InitStruct.Pin = IO1_Pin;
	GPIO_InitStruct.Mode = GPIO_MODE_IT_RISING;
	GPIO_InitStruct.Pull = GPIO_PULLDOWN;
	HAL_GPIO_Init(IO1_GPIO_Port, &GPIO_InitStruct);
	

}

/** 
 * NVIC Configuration
 */
void MX_NVIC_Init(void) {
	/* EXTI4_15_IRQn interrupt configuration */
	HAL_NVIC_SetPriority(EXTI4_15_IRQn, 0, 0);
	HAL_NVIC_EnableIRQ(EXTI4_15_IRQn);
}
